# -*- coding: utf-8 -*-
from django.conf.urls.defaults import *
from workflow.views import *


urlpatterns = patterns('',
    # get a dotfile for the referenced workflow
    url(r'^(?P<workflow_slug>\w+)/dotfile/$', dotfile, name='dotfile'),
    # get a png image generated by graphviz for the referenced workflow
    url(r'^(?P<workflow_slug>\w+).png$', graphviz, name='graphviz'),
)
